name: Wan2 Video Generator

on:
  workflow_dispatch:
    inputs:
      video_prompt:
        description: 'Опишите видео на английском'
        required: true
        default: 'A futuristic cyber-punk city during a neon rainstorm, 8k resolution'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Pack
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libsm6 libxext6

    - name: Run Wan-Video Code
      run: |
        git clone https://github.com
        cd Wan2.2
        pip install -r requirements.txt --quiet
        pip install huggingface_hub --quiet
        python -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='Wan-AI/Wan2.2-TI2V-5B', local_dir='../model')"
        python generate.py --model_type "t2v" --ckpt_dir "../model" --prompt "${{ github.event.inputs.video_prompt }}" --image_size "832x480" --frame_num 81 --offload_model True --t5_cpu --save_file "../result.mp4"

    - name: Save Video Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-generated-video
        path: result.mp4
